//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradebook.DAL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmptyTable
    {
        public int AssignmentID { get; set; }
        public string Description { get; set; }
        public string PointsPossible { get; set; }
        public string Category { get; set; }
    }
}
