//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradebook.DAL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class testTable
    {
        public int ID { get; set; }
        public string Column1 { get; set; }
        public string Column2 { get; set; }
    }
}
