//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradebook.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public Assignment()
        {
            this.Undertakes = new HashSet<Undertake>();
        }
    
        public int PointsPossible { get; set; }
        public string Description { get; set; }
        public int GradeID { get; set; }
        public int AssignmentID { get; set; }
    
        public virtual GradeDistribution GradeDistribution { get; set; }
        public virtual ICollection<Undertake> Undertakes { get; set; }
    }
}
