//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradebook.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.GradeDistributions = new HashSet<GradeDistribution>();
            this.Students = new HashSet<Student>();
        }
    
        public int CourseID { get; set; }
        public string CourseNumber { get; set; }
        public string Term { get; set; }
        public int Year { get; set; }
        public string Description { get; set; }
        public int TeacherID { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<GradeDistribution> GradeDistributions { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
